del f:\library\develop\conversionready\compare.lst
fc F:\library\plb_src\INFO.pls.pls f:\library\develop\conversionready\backup\INFO.pls > f:\library\develop\conversionready\compare.lst
fc F:\library\plb_src\integral.pls  f:\library\develop\conversionready\backup\integral.pls >> f:\library\develop\conversionready\compare.lst
fc F:\library\plb_src\nadj002l.pls  f:\library\develop\conversionready\backup\nadj002l.pls >> f:\library\develop\conversionready\compare.lst
fc F:\library\plb_src\NCHK002L.pls  f:\library\develop\conversionready\backup\NCHK002L.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NCMP0002.pls  f:\library\develop\conversionready\backup\NCMP0002.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\ncmp002a.pls  f:\library\develop\conversionready\backup\ncmp002a.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\ncmp002b.pls  f:\library\develop\conversionready\backup\ncmp002b.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NDAT0003.pls  f:\library\develop\conversionready\backup\NDAT0003.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NDAT0004.pls  f:\library\develop\conversionready\backup\NDAT0004.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NDAT0005.pls  f:\library\develop\conversionready\backup\NDAT0005.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\ndat0014.pls  f:\library\develop\conversionready\backup\ndat0014.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NDAT0016.pls  f:\library\develop\conversionready\backup\NDAT0016.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NDAT0020.pls  f:\library\develop\conversionready\backup\NDAT0020.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NDAT0022.pls  f:\library\develop\conversionready\backup\NDAT0022.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NDAT0026.pls  f:\library\develop\conversionready\backup\NDAT0026.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\ndat002a.pls  f:\library\develop\conversionready\backup\ndat002a.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NDAT0030.pls  f:\library\develop\conversionready\backup\NDAT0030.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\ndat0031.pls  f:\library\develop\conversionready\backup\ndat0031.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NDAT0036.pls  f:\library\develop\conversionready\backup\NDAT0036.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NDAT0038.pls  f:\library\develop\conversionready\backup\NDAT0038.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\ndat0041.pls  f:\library\develop\conversionready\backup\ndat0041.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\ndat0042.pls  f:\library\develop\conversionready\backup\ndat0042.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NDAT0050.pls  f:\library\develop\conversionready\backup\NDAT0050.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NEOM0026.pls  f:\library\develop\conversionready\backup\NEOM0026.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NEwb0001.pls  f:\library\develop\conversionready\backup\NEwb0001.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NGUA0002.pls  f:\library\develop\conversionready\backup\NGUA0002.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NINC0007.pls  f:\library\develop\conversionready\backup\NINC0007.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\ninv0001.pls  f:\library\develop\conversionready\backup\ninv0001.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\ninv0007.pls  f:\library\develop\conversionready\backup\ninv0007.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NINV0010.pls  f:\library\develop\conversionready\backup\NINV0010.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NINV0013.pls  f:\library\develop\conversionready\backup\NINV0013.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NINV0016.pls  f:\library\develop\conversionready\backup\NINV0016.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NINV002L.pls  f:\library\develop\conversionready\backup\NINV002L.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NLCR002L.pls  f:\library\develop\conversionready\backup\NLCR002L.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NLCR0038.pls  f:\library\develop\conversionready\backup\NLCR0038.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NLCR0040.pls  f:\library\develop\conversionready\backup\NLCR0040.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NLCR0041.pls  f:\library\develop\conversionready\backup\NLCR0041.pls >> f:\library\develop\conversionready\compare.lst 
fc f:\library\plb_src\NORD0003.pls  f:\library\develop\conversionready\backup\NORD0003.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NORD0004.pls  f:\library\develop\conversionready\backup\NORD0004.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\nord0005.pls  f:\library\develop\conversionready\backup\nord0005.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\nord0006.pls  f:\library\develop\conversionready\backup\nord0006.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\nord0007.pls  f:\library\develop\conversionready\backup\nord0007.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NORD0013.pls  f:\library\develop\conversionready\backup\NORD0013.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NORD0016.pls  f:\library\develop\conversionready\backup\NORD0016.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NORD0023.pls  f:\library\develop\conversionready\backup\NORD0023.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NORD0024.pls  f:\library\develop\conversionready\backup\NORD0024.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\nord0026.pls  f:\library\develop\conversionready\backup\nord0026.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\nord002l.pls  f:\library\develop\conversionready\backup\nord002l.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\nord0033.pls  f:\library\develop\conversionready\backup\nord0033.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NORD013B.pls  f:\library\develop\conversionready\backup\NORD013B.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NORD013D.pls  f:\library\develop\conversionready\backup\NORD013D.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NORD013X.pls  f:\library\develop\conversionready\backup\NORD013X.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\nordtest.pls  f:\library\develop\conversionready\backup\nordtest.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NPRO0001.pls  f:\library\develop\conversionready\backup\NPRO0001.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\nrco0001.pls  f:\library\develop\conversionready\backup\nrco0001.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NSCH0001.pls  f:\library\develop\conversionready\backup\NSCH0001.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NSHP0001.pls  f:\library\develop\conversionready\backup\NSHP0001.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\nshp0002.pls  f:\library\develop\conversionready\backup\nshp0002.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\NSHP0006.pls  f:\library\develop\conversionready\backup\NSHP0006.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\nspr0001.pls  f:\library\develop\conversionready\backup\nspr0001.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\nxch0001.pls  f:\library\develop\conversionready\backup\nxch0001.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\nxch0003.pls  f:\library\develop\conversionready\backup\nxch0003.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\nxch003b.pls  f:\library\develop\conversionready\backup\nxch003b.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\STAT0004.pls  f:\library\develop\conversionready\backup\STAT0004.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\STAT0005.pls  f:\library\develop\conversionready\backup\STAT0005.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\stat0007.pls  f:\library\develop\conversionready\backup\stat0007.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\STAT0008.pls  f:\library\develop\conversionready\backup\STAT0008.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\STAT008b.pls  f:\library\develop\conversionready\backup\STAT008b.pls >> f:\library\develop\conversionready\compare.lst 
fc F:\library\plb_src\STAT008C.pls  f:\library\develop\conversionready\backup\STAT008C.pls >> f:\library\develop\conversionready\compare.lst
