.///////////////////////////////////////////////////////////////////////////////
.//
.//   Program:   appbottom.inc
.//
.//    Author:   bjackson@adjacency.net
.//
.// Copyright:   © 2004 Adjacency Consulting Group, Inc.  All rights reserved.
.//
.//      Date:   3 December 2004
.//
.//   Purpose:   Encapsulate required top-of-program inclusions
.//
.//  Revision:
.//              ver03   29 DEC 2005     ASH - ADDED WEBSITE TRACKING FILE
.//              ver02   13 DEC 2005     ASH - ADDED CONSULTANT FILE
.//              ver01   03 DEC 2004     BJACKSOn
.//
.///////////////////////////////////////////////////////////////////////////////
	include 	comlogic.inc
    include compio.inc
    include cntio.inc
    include ndatio.inc
    include nxrfio.inc
    include nordio.inc
.START PATCH 02 ADDED LOGIC
    include ncltio.inc
.END PATCH 02 ADDED LOGIC
.START PATCH 03 ADDED LOGIC
    include nwebio.inc
.END PATCH 03 ADDED LOGIC
.///////////////////////////////////////////////////////////////////////////////
