              INclude         Common.inc
              include         Nowndd.inc
Own           Ifile           KEYLEN=4,FIXED=190                            
              
              
test          OPen           Own,"\\nts1\e\data\index\ninown.isi"
              keyin           str1
              stop
              
              
              
              include         Nownio.inc              