Copy \\nts1\e\apps\winbatch\live\butil.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\butiljd.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\butilold.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\checks.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\checksboa.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\checksboa2.wbt \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\checksjd.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\checkstest.wbt \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\Checkstmp.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\checkszip.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\creditcheck.wbt \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\dailyjd.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\datapick.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\dbnordhour.wbt \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eom1st.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eom1stjd.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eom2nd.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eom2ndjd.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eom3rd.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eom3rd0929.wbt \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eom3rdDM.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eom3rdjd.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eom3rdjd2.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eom3rdjl.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eom3rdnew.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eom3rdoar.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\Eom4th.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eomah.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eomauto.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eomautojd.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eomjob.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eomjob2.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eomjobjd.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\EOMLASTdm.WBT  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eomlp.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eomlp2.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\eomoarjd.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\faxesmtp.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\faxlcr.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\faxord.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\faxord2.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\faxordjd.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\faxship.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\friday.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\fridayjd.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\fridayMini.wbt \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\ftptdmc2.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\loinc.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\mailplan.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\misc.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\moapurge.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\monday.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\monday1013.wbt \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\monday2.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\Ncardupd.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\ninv.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\ninvjd.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\nordaily.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\Nordailyjd.wbt \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\nordhour.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\nordhourdm.wbt \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\nordhourjd.wbt \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\nordhourjd2.wb \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\nordprt.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\nordprtjd.wbt  \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\ordersum.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\rentexch.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\Rentexchlist.wBT \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\saturday.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\shipreq.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\tcdown2.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\tdmccomm.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\tdmccommjd.wbt \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\trifiles.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\unbill.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\unbillgs.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\unbilljd.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\unbilljl.wbt   \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\WebcardFtpHome.WBT \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\webcardsjd.wbt \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\winrev.wbt    \\nts1\e\library\develop\nts08\
Copy \\nts1\e\apps\winbatch\live\winrevd.wbt    \\nts1\e\library\develop\nts08\
