;    Last change:  JS    3 Feb 2000    2:54 pm
. .............................................................................
.CONTACT1/INC
. .CONTACT TABLE USED FOR DISPLAY AND PRINT PROGRAMS
. 
OCNT      DIM       40
OCNT0    INIT      "Billing(415) 291-5621"
OCNT1    INIT      "Suzie McGuire(415) 291-5637"
OCNT2    INIT      "Catherine Osuna(415) 291-5665"
.OCNT2    INIT      "jennifer ost" left 9/92
.OCNT2    INIT      "glendi henion"
.OCNT3    INIT      "laura trupin"
OCNT3    INIT      "Jereza Mendoza(415) 291-5656"
.OCNT4    INIT      "tina maultsby"
.OCNT4    INIT      "catherine veyna"
.OCNT4    INIT      "melinda rivera"     1/8/92
.OCNT4    INIT      "stacey white"      3/2/93
OCNT4     INIT      "Jeanette Cassano(415) 291-5644"
.OCNT4    INIT       "leola wong"   5/93     
OCNT5     INIT      "Elki Taba(415) 291-5669"
.OCNT5     INIT      "Mary Gregory(415) 291-5669"
.OCNT5    INIT      "jennifer post"
.OCNT5    INIT      "marguerite salmon"
.OCNT5    INIT      "jason cambern"
.OCNT5    INIT      "derek glass"
.OCNT6    INIT      "michael dekker"
.OCNT6    INIT      "karen gallion"
OCNT6    INIT      "Gillian Cavana(415) 291-5668"
.OCNT6    INIT      "Elissa Buchanan(415) 291-5668" 11/10/97
.OCNT7    INIT      "linda mietus"
.OCNT7    INIT      "Cheryl Piry(415) 291-5667" 12/98
.OCNT7    INIT      "Laramie Howard(415) 291-5667" 01/10/2000
OCNT7    INIT      "Shana Betner (415) 291-5621"
.OCNT8   INIT      "Jone rabaino"
.OCNT8    INIT      "michael garland"
.OCNT8    INIT      "liora natelson"
.OCNT8    INIT      "Crispin Herrick(415) 291-5655" 4/1/98
.OCNT8    INIT      "Marilyn Brookins(415) 291-5609"
OCNT8    INIT      "Lisa Chapin(415) 291-5609"
.OCNT9    INIT      "elizabeth corsale"
OCNT9    INIT      "Phoebe Fearing(415) 291-5667"
.OCNT9    INIT      "Nancy Purcell(415) 291-5638" 5/1/98
OCNT10   INIT      "Steve Kehrli(415) 291-5640"
.OCNT11   INIT      "james eves"
.OCNT11   INIT      "sonya brown"
.OCNT11   INIT      "julie doherty"            .4/28/94
.OCNT11   INIT      "hillary harper"           .7/19/94
.OCNT11   INIT      "rebecca mumma(415) 291-5640"
.OCNT11   INIT      "Brendan Peterson(415) 291-5603"
OCNT11   INIT      "Bonnie Olson(415) 291-5647"
.OCNT12   INIT      "marguerite salmon"  cold calls
OCNT12   INIT      "Susan Anstrand(415) 291-5643"
.OCNT13   INIT      "yolanda montes"
.OCNT13   INIT      "robert santiago"
.OCNT13   INIT      "meg van wagenen" left sales 7/93.
.OCNT13   INIT      "kathleen pavao"
.OCNT13   INIT      "Brenda Villanueva(415) 291-5657" 5/31/98
OCNT13   INIT      "Becky Chavez(415) 291-5657"     08/04/98
.OCNT14   INIT      "tiffany figoni"
OCNT14   INIT      "Brian Schulz(415) 291-5642"
.OCNT15   INIT      "kim kouri"
OCNT15   INIT      "Brian Karo(415) 291-5663"
.OCNT15   INIT      "laurie williams"
OCNT16   INIT      "Jane Nagatoshi(415) 291-5662"
OCNT17   INIT      "Greg Kettering(415) 291-5658"
...............................................................................
.PROGRAMS ACCESSING THIS INCLUDE:
.
.   NAME         ACCESS TYPE
.***********    ********************************************
.NORD0001
.NORD002L
.NORD0009
.NORD0033
.NINV0001
.NINV0003
.NXCH0001
.********> END IF INCLUDE
