;    Last change:  JS   26 Aug 1999    2:37 pm
. .............................................................................
. NIN CONTACT TABLE - FOR LCR'S PROGRAMS:
.		      NLCR0001, NLCR0002
. ..................
. 
CNT	 DIM	   20			      DISPLAY FIELD.
CNT0	 INIT	   "Sales()"
CNT1	 INIT	   "Jereza Mendoza(415) 291-5656"
CNT2	 INIT	   "Laramie Howard(415) 291-5667"
CNT3	 INIT	   "Jeanette Cassano(415) 291-5644"
CNT4	 INIT	   "Gillian Cavana(415) 291-5668"
CNT5	 INIT	   "Becky Chavez(415) 291-5657"
CNT6	 INIT	   "Phoebe Fearing(415) 291-5621"
CNT7	 INIT	   "Bonnie Olson(415) 291-5647"
CNT8	 INIT	   "Brian Karo(415) 291-5663"
CNT9	 INIT	   "Kattt Sammon(415) 291-5646"
CNT10	 INIT	   "Elki Taba(415)291-5669"
CNT11	 INIT	   "Steve Kehrli(415) 291-5640"
CNT12	 INIT	   "Catherine Osuna(415) 291-5665"
CNT13	 INIT	   "Brian Schulz(415) 291-5642 "
CNT14	 INIT	   "Jane Nagatoshi(415) 291-5662"
CNT15	 INIT	   "Lisa Chapin(415) 291-5609"
CNT16	 INIT	   " ()"
CNT17	 INIT	   " ()"
CNT18	 INIT	   " ()"
. *****************>END OF INCLUDE.

