;.............................................................
. Patch 1.1 ASH 12/29/2004 - Mailer/Broker Conversion
.
.DTPFile        Ifile          Key=8,fixed=40
.DTPFlag        Form            1
.DTPName        Init           "DaysToPay"
.;Workvars
.DTPFld         Dim            8
.;
.DTPbroker      Dim            4            1-4
.DTPMailer      Dim            4            5-8
.DTP3yrcount    form           5            9-13
.DTP3yrDays     Form           9           14-22
.DTP1yrcount    form           5           23-27
.DTP1yrDays     Form           9           28-36
.DTPFill        Dim            4           37-40
..............................................................
DTPFile        Ifile          Key=12,fixed=44
DTPFlag        Form            1
DTPName        Init           "DaysToPay|NINS1:502             "
.;Workvars
DTPFld         Dim            12
.;
DTPbroker      Dim            6            1-6
DTPMailer      Dim            6            7-12
DTP3yrcount    form           5           13-17
DTP3yrDays     Form           9           18-26
DTP1yrcount    form           5           27-31
DTP1yrDays     Form           9           32-40
DTPFill        Dim            4           41-44
.;.............................................................
