;HTMLCGICons.inc
;///////////////////////////////////////////////////////////////////////////////
cgiInput        dim         ^
countString     dim         5
cwk5            dim         5
environment     dim         260
food            dim         260
newCount        dim         5
ordinal         dim         260
relative1       dim         260
relative2       dim         260
varValue        dim         260

count           form        5
nwk5            form        5
debug           dim 20

i               integer     4
;///////////////////////////////////////////////////////////////////////////////
