        include common.inc
        include cons.inc
        include norddd.inc
        include nmlrdd.inc
        include nmlr2dd.inc
        include nxrfdd.inc
        include nbrkdd.inc
        include nbrk2dd.inc
        include ndatdd.inc
        include nrtndd.inc
        include nmdldd.inc
        include nusedd.inc

.Pointers to Objects
InfoWindPtr     Window  ^
InfoEditPtr     EditText ^
InfoEditPtr1    EditText ^
.Actual Objects
InfoListView    ListView
InfoEditText    EditText
DimPtr  Dim     ^
DimPtr1 Dim     ^
DimPtr2 Dim     ^
DimPtr3 Dim     ^
FrmPtr  Form    ^
.
OrderInfoString dim     47
ScrRight form   4
ScrBottom form  4 
MouseForm form  10
FarRight form   4
FarBottom form  4
T1      form    4
L1      form    4

        include nordio.inc
        include nmlrio.inc
        include nmlr2io.inc
        include nxrfio.inc
        include nbrkio.inc
        include nbrk2io.inc
        include ndatio.inc
        include nrtnio.inc
        include nmdlio.inc
        include nuseio.inc
        include comlogic.inc
