;    Last change:  JD   14 Mar 2001    1:35 pm
. .............................................................................
. MEDIA TABLE.
. ............
.
.media28  dim       28       05sep02 jd added ftp.
.media25  dim       28       17jul98 jd added email.
.media    dim       28       16jul96 added 23   
.media    dim       28          
MEDIA    DIM       50                 .17jun96
.
MED0     INIT      "MT 9t 1600/6250 BPI or 3480 cartridges (non-IRDC)"
MED1     INIT      "Diskette         "
MED2     INIT      "4-across cheshire"
MED3     INIT      "Press.sens.labels"
MED4     INIT      "IBM 3480 tape cartridge"
MED5     INIT      "1-up cheshire"
MED6     INIT      "Package inserts"
MED7     INIT      "Mag tape 9t 1600 BPI"
MED8     INIT      "Mag tape 9t 800 or 1600 BPI"
MED9     INIT      "Match-col tp"
MED10    INIT      "Magtape 9t 1600/6250,3480 cart.(non-IRDC) $15flt"
MED11    INIT      "Magtape 9t 1600/6250,3480 cart.(non-IRDC) $20flt"
MED12    INIT      "Magtape 9t 1600/6250,3480 cart.(non-IRDC) $25flt"
MED13    INIT      "Magtape 9t 1600/6250,3480 cart.(non-IRDC) $30flt"
MED14    INIT      "Magtape 9t 1600 $15flt"
MED15    INIT      "Magtape 9t 1600 $20flt"
MED16    INIT      "Magtape 9t 1600 $25flt"
MED17    INIT      "Magtape 9t 1600 $30flt"
MED18    INIT      "Press.sens.labels @ $7/m"
MED19    INIT      "Mag tape see special inst"
MED20    INIT      "                           "
.MED20    INIT      "really used billing purposes."
MED21    INIT      "Press.sens.labels @ $10/m"
MED22    INIT      "3480 tape cartridge (non-IRDC) $25flt"
MED23    INIT      "MT 9t 1600/6250 BPI "
MED24    INIT      "3480 tape cartridge (non-IRDC)"
MED25    INIT      "Email @ $50"
MED26    INIT      "Email"
MED27    INIT      "IBM 3480 tape cartridge (non-IRDC) $30flt"
MED28    INIT      "FTP"
MED29    INIT      " "

