. .............................................................................
. MEDIA TABLE.
. ............
.
MEDIA    DIM       28
.
MED0     INIT      "MAG TAPE 9T 1600 OR 6250 BPI"
MED1     INIT      "DISKETTE         "
MED2     INIT      "4-ACROSS CHESHIRE"
MED3     INIT      "PRESS.SENS.LABELS"
MED4     INIT      "IBM 3480 TAPE CARTRIDGE"
MED5     INIT      "1-UP CHESHIRE"
MED6     INIT      "PACKAGE INSERTS"
MED7     INIT      "MAG TAPE 9T 1600 BPI"
MED8     INIT      "MAG TAPE 9T 800 OR 1600 BPI"
MED9     INIT      "MATCH-COL TP"
MED10    INIT      "MAGTAPE 9T 1600/6250 $15FLT"
MED11    INIT      "MAGTAPE 9T 1600/6250 $20FLT"
MED12    INIT      "MAGTAPE 9T 1600/6250 $25FLT"
MED13    INIT      "MAGTAPE 9T 1600/6250 $30FLT"
MED14    INIT      "MAGTAPE 9T 1600 $15FLT"
MED15    INIT      "MAGTAPE 9T 1600 $20FLT"
MED16    INIT      "MAGTAPE 9T 1600 $25FLT"
MED17    INIT      "MAGTAPE 9T 1600 $30FLT"
MED18    INIT      "PRESS.SENS.LABELS @ $7/M"
MED19    INIT      "MAG TAPE SEE SPECIAL INST"
MED20    INIT      "                           "
.MED20    INIT      "really used by dummy orders"
MED21    INIT      "PRESS.SENS.LABELS @ $10/M"
MED22    INIT      "                           "
MED23    INIT      "                           "
MED24    INIT      "                           "
MED25    INIT      "                           "

