. .............................................................................
. 
. *** VARIABLES USED IN DATE HANDLING ROUTINES.
.
. .............................................................................
.  
DATE     DIM       6        DATE
DATE1    FORM      6
DATEM1   FORM      2        TEMP VARIABLE USED FOR EDIT CHECKS
DATEM2   FORM      2        TEMP VARIABLE USED FOR EDIT CHECKS
.CC       FORM      "19"     CENTURY
YYMMDD   FORM      6        DATE IN YYMMDD FORMAT (USED FOR DATE COMPARISON).
DAYSMO   FORM      2        DAYS IN THE MONTH
LEAPYR   DIM       1        LEAPYR = 'Y' IF LEAP YEAR; 'N' IF NOT
KEYDAT   DIM       1        'Y' IF VALID DATE INPUT.
MMNAM    DIM       3        MONTH NAME
. 
. .............................................................................

