	INCLUDE	NORDDD.INC
	INCLUDE	NORDIO.INC
nordddfieldcount init  75
nordddarray	dim 20(nordddfieldcount,3),"ORCODE","1","Order Code":
					"OSTAT","1","Order Stattus":
					"OMLRNUM","4","Mailer Number":
					"OLRN","6","LR Number":
					"OCOBN","3","Mailer Contact":
					"OLNUM","6","List Number":
					"OLON","4","List Owner Number":
					"OMLRPON","12","Mailer PO Number":
					"OQTY","9","Order Quantity":
					"OPPM","5","Price - Obsolete":
					"OMLRKY","12","Mailer Key":
					"OFOCODE","2","Furnish Code:
					"ORTNDTEC","2","Return Date - CC":
					"ORTNDTEY","2","Return Date - YY":
					"ORTNDTEM","2","Return Date - MM":
					"ORTNDTED","2","Return Date - DD":
					"OMDTEC","2","Mail Date - CC":
					"OMDTEY","2","Mail Date - YY":
					"OMDTEM","2","Mail Date - MM":
					"OMDTED","2","Mail Date - DD":
					"OTOCODE","1","Test Code":
					"OSOTCODE","1","Sel./Test - Obsolete":
					"OCCODE","1","Cont. Code":
					"OLRNCO","6","Cont. LR":
					"OODTECOC","2","Cont. Order Date-CC":
					"OODTECOY","2","Cont. Order Date-YY":
					"OODTECOM","2","Cont. Order Date-MM":
					"OODTECOD","2","Cont. Order Date-DD":
					"OQTYCO","9","Cont. Order Qty":
					"OSPI","24","Spec. Instruct. - Obs":
					"OBildrct","1","Bill Direct Code":
					"OBRKGUAR","1","Broker Guarantee":
					"OELCODE","1","Entire Code":
					"OODNUM","7","Offer Number":
					"OODES","5","Offer Des. - Obs.":
					"ONETQTY","9","Net Quantity":
					"OCAMP","6","Campaign Number":
					"OCLRSTAT","1","Clearance Status":
					"OCLRINIT","3","Clearance Inits":
					"OBRKRPT","1","Outside Broker Code":
					"OCLRDTEC","2","Clear Date - CC":
					"OCLRDTEY","2","Clear Date - YY":
					"OCLRDTEM","2","Clear Date - MM":
					"OCLRDTED","2","Clear Date - CCDD:
					"ORENT","1","LCR Rent Request":
					"OHIST","1","History code":
					"OXPPM","5","Exchange PPM":
					"ORTNNUM","4","Rtn-To Number":
					"OTAPERET","1","Tape Return":
					"OUQTY","9","Universe Qty - Obs.":
					"OSALES10","1","Salesperson - tens":
					"OSALES","1","Salesperson - ones":
					"OCOCODE","2","NIN Contact":
					"OCO2CODE","2","NIN Caller":
					"OODTEC","2","Order Date - CC":
					"OODTEY","2","Order Date - YY":
					"OODTEM","2","Order Date - MM":
					"OODTED","2","Order Date - DD":
					"OSCODE","1","Sample Code":
					"OCOMSLCT","1","COMSELECT":
					"OSHP","2","Shipping Code":
					"O1DES","35","List Name":
					"O2DES","35","Select Name":
					"OREUSE","6","RE-USE LR":
					"ODOWJ","3","Typist":
					"OEXQTY","9","Exchange Qty":
					"GUARCODE","1","NIN Guarantee":
					"OBRKNUM","4","Broker Number":
					"OBRKCNT","3","Broker Contact":
					"osamcde","3","Sample Number":
					"onetper","2","Net Name %":
					"onetrc","3.2","Net Name Running":
					"onetfm","1","Net Code":
					"onetmin","7","Net Name Minimum":
					"ofiller","80","Filler"