;    Last change:  JD   4 May  2005   12:25 pm
;    Last change:  JD   25 Jan 1999   12:25 pm
*..............................................................................
* OSLSTEAMS/INC -   ORDER SALES TEAMS TABLE.     01FEB89
*..............................................................................
.AUG312005 Replaced Suzie's Team with Ann's Team
.
OSLS0    INIT      "NO SALESPERSON "
OSLS1    INIT      "JEANETTE'S TEAM "
.OSLS2    INIT      "REBECCA'S TEAM "
OSLS2    INIT      "DELYNNE'S TEAM"
OSLS3    INIT      "SUSAN'S TEAM"
OSLS4    INIT      "            "
.OSLS4    INIT      "NANCY'S TEAM "
.OSLS5    INIT      "BONNIE'S TEAM "
OSLS5    INIT      "               "
OSLS6    INIT      "LIST MANAGEMENT "
OSLS7    INIT      "ANN'S TEAM "
.OSLS7    INIT      "SUZIE'S TEAM "
.OSLS8    INIT      "COLD CALLS "
OSLS8    INIT      "             "
OSLS9    INIT      "           "
.OSLS9    INIT      "EM's team        "
.OSLS10   INIT      "TIFFANY'S TEAM"
OSLS10   INIT      "               "
OSLS11   INIT      "   "
OSLS12   INIT      "  "
OSLS13   INIT      " "
OSLS14   INIT      " "
OSLS15   INIT      " "
OSLS16   INIT      " "
OSLS17   INIT      " "
OSLS18   INIT      " "
OSLS19   INIT      " "
OSLS20   INIT      " "
.OSLS21   INIT      " "
.OSLS22   INIT      " "
.OSLS23   INIT      " "
.OSLS24   INIT      " "
.OSLS25   INIT      " "
.OSLS26   INIT      " "
.OSLS27   INIT      " "
.OSLS28   INIT      " "
.OSLS29   INIT      " "
...............................................................................
.ANY CHANGES IN THIS TABLE NEED TO WILL CHANGE TABLE IN Nord0011.dbs. AFTER 
.PARAGRAPH READ2.
...............................................................................
