.patch 1.1 01Apr99 DLH
. .............................................................................
. SHIPPING TABLE
. ..............
.begin patch 1.1
SHIPdesc DIM       26
.SHIP     DIM       26
.end patch 1.1
SHIP0    INIT      "See Special Instructions"
SHIP1    INIT      "Federal/Exp - 2 day"
SHIP2    INIT      "U.P.S. Red label"
SHIP3    INIT      "Federal Express Priority 1"
SHIP4    INIT      "UPS orange/3-day"
SHIP5    INIT      "U.P.S. ground"
SHIP6    INIT      "U.P.S. Blue label"
SHIP7    INIT      "Airborne - 2 day"
SHIP8    INIT      "Airborne express"
SHIP9    INIT      "Federal Express - standard"
.begin patch 1.1
Ship10   INIT      "In House Transfer"
.end patch 1.1

